### PR TITLE
dev-db/dbeaver-bin: bump to v4.2.6

### PR DESCRIPTION
**Pull request by fancywriter**

### CODE REVIEW

**Comment by rindeal** [comment]
A few days ago I gave you a direct commit access to `dev-db/dbeaver-bin`. If I set it up correctly, you should be now able to do something like this:

```sh
git checkout dbeaver
git pull origin dbeaver
cd dev-db/dbeaver-bin
## update stuff ...
git add .
git commit .
git pull --rebase origin master
git push origin dbeaver
## wait for CI to complete
git checkout master
git merge --ff-only dbeaver
git push origin master
```

without the need to create a PR for every bump.

**Comment by fancywriter** [comment]
Oh, right, probably didn't notice that...

**Comment by fancywriter** [comment]
No, push to master still doesn't work.
I have created branch `dbeaver`, but travis didn't trigger anything for this branch.

I have noticed that by configuration travis watches the following branches: **master**, **dev** and all starts with **ci**. I have pushed to **dev** branch, build was finished and passed https://travis-ci.org/rindeal/rindeal-ebuild-repo/builds/313409815

However, push to master still doesn't work
```
remote: error: GH006: Protected branch update failed for refs/heads/master.
remote: error: At least one approved review is required by reviewers with write access.
To github.com:rindeal/rindeal-ebuild-repo.git
 ! [remote rejected] master -> master (protected branch hook declined)
```

**Comment by rindeal** [comment]
Yes, I forgot to mention that Travis is set up so that

```
branches:
    only:
        - master
        - dev
        - /^ci\//
```

trigger builds. Normal branches shouldn't trigger builds because they usually contain dirty code that most certainly fails. What I do is:

1. prepare the code in various branches
2. when mostly ready, rebase onto `dev` branch and FF merge into it
3. cleanup the code inside the `dev` branch
4. when it builds, merge to `master`

This workflow doesn't work well when multiple people are pushing to master, however. So I will have to come up with a better solution. One that comes to my mind is:

1. prepare the code in various branches, eg. `dbeaver`
2. when ready, push to a new branch with a `ci/` prefix ( eg. `git push origin dbeaver:ci/dbeaver`)
3. git push should now trigger the build
5. when OK, merge. I'm not sure though if `dbeaver` or `ci/dbeaver` branch
6. delete remote `ci/dbeaver` branch (`git push origin --delete ci/dbeaver`)

**Comment by rindeal** [comment]
> I have noticed that by configuration travis watches the following branches: master, dev and all starts with ci. I have pushed to dev branch, build was finished and passed https://travis-ci.org/rindeal/rindeal-ebuild-repo/builds/313409815
>
> However, push to master still doesn't work

The push to master doesn't work for you, because the `dev` branch contains some of my no-yet-merged commits, which you don't have access to, because you are allowed to only merge commits that modify `dev-db/dbeaver/*` files. You would have to cherry-pick your commit to make it work.

**Comment by fancywriter** [comment]
No, push to **master** still doesn't work.

**Comment by rindeal** [comment]
Ok, I've disabled the _Require pull request reviews before merging_ option altogether, try now.

**Pull request merged**
